### ISSUE TITLE
[ROADMAP] Points and Ranking 🎰

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#24]
### Why?
Points and rankings are what make games fun and competitive. We need 'em:

### Tasks
- [ ]  Display current points on public profile page
- [ ]  Display points and history on the dashboard
- [ ]  Introduce ranking per repository

**Comment by jobenjada** [comment]
This is done ✅
